### ISSUE TITLE
Scheduled tasks are not cancelled after script unloading/reloading.

### ISSUE THREAD

**Issue by Grabsky** [LuaLink/LuaLink#14]
Tasks does not seem to be cancelled whenever script is unloaded. Steps to test this quickly:

1. Create new script, call it whatever:
    ```lua
    script.onEnable(function()
        utils.scheduleSyncRepeatingTask(function()
            script.logger.info("1")
        end, 20, 20)
    end)
    ```
2. Load the script.
3. Reload it a bunch of times.
4. Unload the script.

This *probably* applies to all kinds of tasks, not only the repeating one.

Perhaps, if improvements to the scheduler are made, maybe it's also good idea to expose the task as function parameter, for example:
```lua
local iterations = 0
utils.scheduleSyncRepeatingTask(function(task)
    -- canceling on third iteration
    if (iterations == 3) then
        task:cancel()
    end
    -- doing something
    script.logger.info("1")
    -- incrementing iterations count
    iterations = iterations + 1
end, 20, 20)
```

**Comment by Saturn745** [comment]
Will look into when I get home.

**Comment by Saturn745** [comment]
> Perhaps, if improvements to the scheduler are made, maybe it's also good idea to expose the task as function parameter, for example:

I do like this but the runnable that the Bukkit scheduler calls does not seem to pass the task so this isn't possible from what I can tell.
However you can achieve something similar like this
```lua
local task
local iterations = 0

local function stopTask()
    utils.cancelTask(task)
end
script.onEnable(function()
    task = utils.scheduleSyncRepeatingTask(function()
        -- canceling on third iteration
        if (iterations == 3) then
            script.logger.info("Stopping task")
            stopTask()
        end
        -- doing something
        script.logger.info("Iteration " .. iterations)
        -- incrementing iterations count
        iterations = iterations + 1
    end, 20, 20)
end)
```
