### ISSUE TITLE
Scripts are loaded before addons are registered, causing load failures.

### ISSUE THREAD

**Issue by Grabsky** [LuaLink/LuaLink#15]
I can think of ~~three~~ two solutions to solve that.

1. Load scripts when `ServerLoadEvent` is called.
2. Register addons on `Plugin#onLoad` and load scripts on `Plugin#onEnable`.

It could also be achieved by making addon loading independent of Paper plugin loader, but that is likely to cause a lot of issues with addon dependencies.

**Comment by Saturn745** [comment]
> Load scripts when ServerLoadEvent is called.

This may be the best option

> Register addons on Plugin#onLoad and load scripts on Plugin#onEnable.
I had considered this but it would limit the ability for addons to hook into other plugins which need to be hooked when the plugin is enabled rather than when it's loaded

> It could also be achieved by making addon loading independent of Paper plugin loader, but that is likely to cause a lot of issues with addon dependencies.
Considered this as well but like you said would have caused some issues with addon dependencies

I would say the best option is when the ServerLoadEvent is triggered unless you have any other ideas to fix this.

**Comment by Saturn745** [comment]
> > I had considered this but it would limit the ability for addons to hook into other plugins which need to be hooked when the plugin is enabled rather than when it's loaded
> 
> That is true.
> 
> > I would say the best option is when the ServerLoadEvent is triggered unless you have any other ideas to fix this.
> 
> Agreed. Seems to be only viable option and nothing else really came to my mind. For the time being `ServerLoadEvent` should get the job done.
> 
> I initially wanted to make a quick PR to fix that, but I see it may require a bit more work than just moving stuff around. 
> 
> Namely, either `script.onLoad` or `script.onEnable` should be removed as nothing is really called on LuaLink load, nor enable. Personally, I think that `script.onLoad` and `script.onUnload` would better represent **script** lifecycle, as `script.onEnable` and `script.onDisable` can be misleading for those who have dealt with Bukkit API before.

Yeah I agree with all of this. I can work on it when I get home if you haven't made a PR.
