### ISSUE TITLE
1.20.2 support??

### ISSUE THREAD

**Issue by jLn0n** [LuaLink/LuaLink#23]
it would be pretty nice if 1.20.2 support is added...

**Comment by Saturn745** [comment]
I just tested on a fresh 1.20.2 server and the plugin works fine :+1: I have gone ahead and updated the Modrinth and Hangar gradle tasks to show that it supports 1.20.2 (https://github.com/LuaLink/LuaLink/commit/a15ecf0df046e0cbf0b4a95b1be31fe8924af28d) and have updated the latest version on both platforms to show that it is supported.

**Comment by jLn0n** [comment]
> I just tested the plugin on a fresh 1.20.2 server, and it works fine! 👍 I've gone ahead and updated the Modrinth and Hangar gradle tasks to indicate that it now supports 1.20.2 ([a15ecf0](https://github.com/LuaLink/LuaLink/commit/a15ecf0df046e0cbf0b4a95b1be31fe8924af28d)). Additionally, I've updated the latest version on both platforms to reflect its compatibility with this version.

thank you for the response..
